steps:
  build-and-push:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      platforms: linux/amd64, linux/arm64
      repo: "${CI_REPO_OWNER##mu-}/${CI_REPO_NAME}"
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
  build-and-push-jruby:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      platforms: linux/amd64, linux/arm64
      repo: "${CI_REPO_OWNER##mu-}/${CI_REPO_NAME/ruby/jruby}"
      tags: latest
      dockerfile: Dockerfile.jruby
      from_secret: docker_username
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
when:
  - event: push
    branch: [master, main]
