steps:
  release:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      platforms: linux/amd64, linux/arm64
      repo: "${CI_REPO_OWNER##mu-}/${CI_REPO_NAME}"
      tags: "${CI_COMMIT_TAG##v}"
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    group: build
  build-and-push-jruby:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      platforms: linux/amd64, linux/arm64
      repo: "${CI_REPO_OWNER##mu-}/${CI_REPO_NAME/ruby/jruby}"
      tags: "${CI_COMMIT_TAG##v}"
      dockerfile: Dockerfile.jruby
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    group: build
when:
  - event: tag
    ref: refs/tags/v*
